using conf:
  default processing mode: Copy
  image default display size:
  - 600
  - 600
  root for file dialog init open: .
  root for tagging results: ./results/
  tags set:
  - Tag0
  - Tag1
  - Tag2
  - Tag3
